import Introduce from "@/components/Header";
import { poppins } from "@/fonts";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="!scroll-smooth">
            <body className={poppins.className}>
                <Header />
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
