import Introduce from "@/components/Introduce";
import { poppins } from "@/fonts";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="!scroll-smooth h-full">
            <body className={poppins.className}>
                <Introduce />
                <Navbar />
                {children}
            </body>
        </html>
    );
}
